@{
    AllNodes = @(
        @{ 
            NodeName="*" 
            psdscallowplaintextpassword = $true
            PSDscAllowDomainUser=$true
        },
         @{
            NodeName="LabSQL2.ss911.net" 
            SQLPath="c:\sql2022"
            SQLDataPath="c:\sqldata"
            SQLLogsPath="c:\sqllogs"
            Environment="D"
         },
         @{
            NodeName="LabSQL3.ss911.net" 
            SQLPath="c:\sql2022"
            SQLDataPath="c:\sqldata"
            SQLLogsPath="c:\sqllogs"
            Environment="D"
         },
         @{
            NodeName="DevDB01.ss911.net" 
            SQLPath="e:\sql2022"
            SQLDataPath="e:\sqldata"
            SQLLogsPath="e:\sqllogs"
            Environment="D"
         },
         @{
            NodeName="TestDB01.ss911.net" 
            SQLPath="e:\sql2022"
            SQLDataPath="e:\sqldata"
            SQLLogsPath="e:\sqllogs"
            LESAAppAutoLogon = $true
            Environment="Q"
         },
         @{
            NodeName="ProdDB01.ss911.net" 
            SQLPath="c:\sql2022"
            SQLDataPath="e:\sqldata"
            SQLLogsPath="f:\sqllogs"
            Environment="P"
         },
         @{
            NodeName="ProdDB02.ss911.net" 
            SQLPath="c:\sql2022"
            SQLDataPath="e:\sqldata"
            SQLLogsPath="f:\sqllogs"
            Environment="P"
         },
         @{
            NodeName="ProdDB03.ss911.net" 
            SQLPath="c:\sql2022"
            SQLDataPath="e:\sqldata"
            SQLLogsPath="f:\sqllogs"
            Environment="P"
         },
         @{
            NodeName="ProdDB04.ss911.net" 
            SQLPath="c:\sql2022"
            SQLDataPath="e:\sqldata"
            SQLLogsPath="f:\sqllogs"
            LESAAppAutoLogon = $true
            RunStateInterface=$true
            Environment="P"
         },
         @{
            NodeName="StandbyDB01.ss911.net" 
            SQLPath="c:\sql2022"
            SQLDataPath="e:\sqldata"
            SQLLogsPath="f:\sqllogs"
            Environment="P"
         },
         @{
            NodeName="StandbyDB02.ss911.net" 
            SQLPath="c:\sql2022"
            SQLDataPath="e:\sqldata"
            SQLLogsPath="f:\sqllogs"
            Environment="P"
         },
         @{
            NodeName="StandbyDB03.ss911.net" 
            SQLPath="c:\sql2022"
            SQLDataPath="e:\sqldata"
            SQLLogsPath="f:\sqllogs"
            Environment="P"
         },
         @{
            NodeName="TrainDB01.ss911.net" 
            SQLPath="c:\sql2022"
            SQLDataPath="e:\sqldata"
            SQLLogsPath="f:\sqllogs"
            Environment="T"
         }
    )
}