@{
    AllNodes = @(
        @{ 
            NodeName="*" 
            psdscallowplaintextpassword = $true
            PSDscAllowDomainUser=$true
        },
        @{
            NodeName="DevIISFarm1.ss911.net" 
            IPAddress="192.103.188.245"
            Websites="Netmenu","RMS","StateInterface"
            Environment="D"
        },
        @{
            NodeName="DevIISFarm2.ss911.net" 
            IPAddress="192.103.188.247"
            Websites="Netmenu","RMS","StateInterface"
            Environment="D"
        },
        @{
            NodeName="DevCEWS01.lesa.net" 
            IPAddress="192.103.188.162"
            Websites="IncidentMapping"
            Environment="D"
        },
        @{
            NodeName="TestIISFarm1.ss911.net" 
            IPAddress="192.103.188.249"
            Websites="Netmenu","RMS","StateInterface"
            Environment="Q"
        },
        @{
            NodeName="TestIISFarm2.ss911.net" 
            IPAddress="192.103.188.251"
            Websites="Netmenu","RMS","StateInterface"
            Environment="Q"
        },
        @{
            NodeName="ProdIISFarm1.ss911.net" 
            IPAddress="192.103.180.88"
            Websites="Netmenu","RMS","StateInterface"
            Environment="P"
        },
        @{
            NodeName="ProdIISFarm2.ss911.net" 
            IPAddress="192.103.180.89"
            Websites="Netmenu","RMS","StateInterface"
            Environment="P"
        },
        @{
            NodeName="DataXfer.lesa.net" 
            IPAddress="192.103.180.56"
            Websites="Jindex"
            Administrators=@("LESA\Dev leads","LESA\ChanK","LESA\EmersonM","LESA\Eng","LESA\ESOCADMonitor","LESA\jindex","LESA\LesaUtilities","LESA\McNamarM","LESA\FossB")
            Environment="P"
        },
        @{
            NodeName="CEWS01.lesa.net" 
            IPAddress="192.103.180.98"
            Websites="IncidentMapping"
            Environment="P"
        },
        @{
            NodeName="TrainIISFarm1.ss911.net" 
            IPAddress="192.103.180.49"
            Websites="Netmenu","RMS","StateInterface"
            Environment="T"
        },
        @{
            NodeName="TrainIISFarm2.ss911.net" 
            IPAddress="192.103.180.55"
            Websites="Netmenu","RMS","StateInterface"
            Environment="T"
        }
    )
}